### ISSUE TITLE
Support for IDN domain names

### ISSUE THREAD

**Issue by lugiber-max** [thundernest/k-9#6767] opened 2023-03-17 11:00 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.509

### Problem you are trying to solve

This is actually a two part issue. When I receive emails with special characters in the domain name they don't get translated into human readable form. E.g they still contain the "xe--" part of the domain name.
The app also crashes when I try to enter an email adress with special characters in it. Like "åäö".
I'd be happy to help out solving this issue if there's something I can do.

### Suggested solution

Adding an IDN domain name parser would hopefully solve this issue.

**Comment by cketti** [comment] 2023-03-17 11:54
While it would be possible to add support for just IDNs, we'll do this as part of adding support for internationalized email.

Duplicate of #2633

**Closed by cketti** 2023-03-17 11:54 UTC
Labels: enhancement
