### ISSUE TITLE
Include Sent Messages in Threads

### ISSUE THREAD

**Issue by maemunman** [thundernest/k-9#6191] opened 2022-07-26 22:12 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.201

### Problem you are trying to solve

I have my Unified Inbox set to include sent items, and I also have message threading enabled. If a thread contains any messages sent by me, it is put in a separate thread. It feels disorganized.

### Suggested solution

If a thread contains messages sent by the user, include those in the same thread rather than a separate one. This is a very practical idea, because it demonstrates the chronology of the conversation.

### Screenshots / Drawings / Technical details

![image92](https://user-images.githubusercontent.com/32847759/181121257-11785f3b-b8d2-4572-b699-3f364b9ae723.png)

**Comment by cketti** [comment] 2022-07-27 14:11
Duplicate of #735

**Closed by cketti** 2022-07-27 14:11 UTC
Labels: enhancement

**Comment by maemunman** [comment] 2022-07-27 16:33
My apologies. I did not see that when I searched; the verbiage is different enough from my own I guess.
