### ISSUE TITLE
Calendar sync support

### ISSUE THREAD

**Issue by aha999** [thundernest/k-9#6411] opened 2022-10-19 17:28 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.202

### Problem you are trying to solve

I would like to sync the calendar from other places, like my desktop Thunderbird client or Google account, and currently, it's not possible to have calendar management in K9Mail app.

### Suggested solution

Calendar/event management functionality should be implemented inside the K9Mail app.

**Comment by cketti** [comment] 2022-10-19 20:59
Duplicate of #6400

**Closed by cketti** 2022-10-19 20:59 UTC
Labels: enhancement
