### ISSUE TITLE
Allow (encrypted) app backups e.g. via SeedVault

### ISSUE THREAD

**Issue by Diapolo** [thundernest/k-9#6252] opened 2022-08-22 08:12 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.301

### Problem you are trying to solve

Current K-9 Mail app doesn't allow encrypted backups via SeedVault (backup App for Android, integrated in LineageOS or CalyxOS, see https://calyxinstitute.org/projects/seedvault-encrypted-backup-for-android).

### Suggested solution

Allow encrypted app backups :).
See https://github.com/seedvault-app/seedvault/wiki/FAQ#why-do-some-apps-not-allow-to-get-backed-up for a description of the problem and see this sample how Transport (Android app for public travel) implemented it: https://github.com/grote/Transportr/commit/4dc38f429f75909a088d8bd8a5b3b5ddd8030f71

**Comment by cketti** [comment] 2022-08-25 15:06
Duplicate of #3857

**Closed by cketti** 2022-08-25 15:06 UTC
Labels: enhancement

**Comment by Diapolo** [comment] 2022-08-25 15:30
@cketti Not exactly, but anyway. Would be nice, if you could take a look at the linked implementation ;-). Any interrest in adding the support?

Am 25. August 2022 15:06:34 UTC schrieb cketti ***@***.***>:
>Duplicate of #3857
>
