### ISSUE TITLE
Improve gmail error handling

### ISSUE THREAD

**Issue by ErikThorsell** [thundernest/k-9#1538] opened 2016-08-03 11:41 UTC
### Expected behavior

I should have been able to securely connect to my email.
### Actual behavior

I was shown the following two screens:

![screenshot_20160803-072217](https://cloud.githubusercontent.com/assets/5284470/17364012/b6f3d23c-594b-11e6-839c-0f56f723d086.png)

![screenshot_20160803-072229](https://cloud.githubusercontent.com/assets/5284470/17364019/bd7ed8cc-594b-11e6-8d19-696960d6f98c.png)

I also got an email to said account telling me that an non trusted app was trying to connect to my account. 

By activating 2FA (which everyone should do regardless) and create an app password I was able to add my account. I know neither if this is a good thing, nor if this is supposed to happen. A more descriptive error and a check to see what's going one would be nice! 
### Steps to reproduce
1. Create new Gmail account.
2. Try to add it to K9 using your Google credentials.
### Environment

K-9 Mail version: 5.010

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): Default (IMAP I assume)

**Comment by philipwhiuk** [comment] 2016-08-04 09:57
Duplicate of #655 There are several work-arounds, one of which is using an app-specific password.

**Comment by Valodim** [comment] 2016-08-04 11:27
It looks like xoauth is not gonna make it into the stable.

I think we should handle this specific error in the meantime, informing the user that they need an app specific password in a less threatening way.

**Closed** 2022-09-09 15:44 UTC
Labels: enhancement
