### ISSUE TITLE
Support for NTFY push notifications

### ISSUE THREAD

**Issue by dessalines** [thundernest/k-9#6869] opened 2023-05-03 11:48 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

Any version

### Problem you are trying to solve

I'd lke to be able to use the ntfy / unified push notification framework to be able to receive notifs, and save on battery.

### Suggested solution

k9 integration with unifiedpush.

**Comment by cketti** [comment] 2023-05-03 12:24
Duplicate of #5165

**Closed by cketti** 2023-05-03 12:24 UTC
Labels: enhancement
