### ISSUE TITLE
Adding multiple recipients from address book only A field is accessible

### ISSUE THREAD

**Issue by Dret42** [thundernest/k-9#7277] opened 2023-10-21 16:43 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.602

### Problem you are trying to solve

To reproduce the lack of feature:
1) Select multiple recipients in your adress book,
2) Select "Send an Email",
3) Select K-9 as email app to use,
4) K-9 start with all recipents in A field and there is no possibility to "move" them into CC or CCN fields (in Thunderbird you can drag and drop from a field to another).

This feature is important when you send an email to a large number of recipients in respect of privacy

### Suggested solution

Possible solutions:

1) Allow to move one or multiple recipients form A field to CC or CCN fields,
2) K-9 colud ask (before where to past the recipents list,
3) Possibility to "switch" the A field into CC o CCN fields.

**Comment by cketti** [comment] 2023-10-21 16:51
Duplicate of #5747

**Closed by cketti** 2023-10-21 16:51 UTC
Labels: enhancement, unconfirmed
