### ISSUE TITLE
Allows to store sent email in same folder as replied message

### ISSUE THREAD

**Issue by cpontvieux-systra** [thundernest/k-9#6573] opened 2023-01-13 09:47 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.400

### Problem you are trying to solve

When I reply to an email, the sent email is stored in configured `Sent folder`. I want an option to store a reply-email to store the sent email in the same folder as the original email (the one I reply to).

### Suggested solution

Either:
- an option in parameters to always store in same folder for a reply to email
- an option to show a new widget in email redaction to select the folder where to store the email (with by default being `Sent folder`)
- the combination of the two above

### Screenshots / Drawings / Technical details

With the option activated:
```
← Write LinkBtn SendBtn SandwitchBtn
From: your@email      ↓
To: ...               ↓
Store in: Send folder ↓
Subject here
Email body
```

**Comment by cketti** [comment] 2023-01-13 09:50
Duplicate of #2266

**Closed by cketti** 2023-01-13 09:50 UTC
Labels: enhancement
