### ISSUE TITLE
improve archive folder tree

### ISSUE THREAD

**Issue by CekLive** [thundernest/k-9#6747] opened 2023-03-10 17:56 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.509

### Problem you are trying to solve

Clearer archive folder tree, K-9 will be used by Thunderbird users, so resuming some of the original Thunderbird interface would be logical

### Suggested solution

see attached screenshot

### Screenshots / Drawings / Technical details

![Tree](https://user-images.githubusercontent.com/127445378/224388895-dab07072-7268-402d-a215-7723dc7dc867.jpg)

**Comment by cketti** [comment] 2023-03-10 17:59
Since you've added a comment to it, you already know that an issue for this feature already exists. Opening another issue only increases work for the maintainers, but doesn't get the feature implemented any faster.

Duplicate of #630

**Closed by cketti** 2023-03-10 17:59 UTC
Labels: enhancement
