### ISSUE TITLE
s/mime support

### ISSUE THREAD

**Issue by quillfires** [thundernest/k-9#6645] opened 2023-02-08 20:13 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.506

### Problem you are trying to solve

use s/mime certificates to sign emails

### Suggested solution

provide support via in app cert repo or use user certs installed to the device

**Comment by cketti** [comment] 2023-02-08 20:18
Duplicate of #1003

**Closed by cketti** 2023-02-08 20:18 UTC
Labels: enhancement
