### ISSUE TITLE
Embed hyperlink

### ISSUE THREAD

**Issue by RyanGibb** [thundernest/k-9#7137] opened 2023-08-20 14:57 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.602

### Problem you are trying to solve

I'm trying to embed a hyperlink in an email's content.

### Suggested solution

Support for embedding a hyperlink. Does K-9 not support HTML composition?

**Comment by cketti** [comment] 2023-08-31 22:44
K-9 Mail currently doesn't support any formatting options when composing a message, including adding links. It will attempt to turn http(s) URLs into links, though.

Duplicate of #1745

**Closed by cketti** 2023-08-31 22:44 UTC
Labels: enhancement
