### ISSUE TITLE
Dark widget please

### ISSUE THREAD

**Issue by Maetts** [thundernest/k-9#6821] opened 2023-04-13 20:21 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.600

### Problem you are trying to solve

Dark widget when dark mode. I know there are prios but please.. 

### Suggested solution

Dark widget would be a very pleasant surprise

**Comment by ByteHamster** [comment] 2023-04-14 11:03
Duplicate of #3728

**Closed by ByteHamster** 2023-04-14 11:03 UTC
Labels: enhancement
