### ISSUE TITLE
Ability to move multiple Mails in one go to subfolder from merged inbox. 

### ISSUE THREAD

**Issue by joeherwig** [thundernest/k-9#6469] opened 2022-11-11 08:32 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.202

### Problem you are trying to solve

I'd like to multi select emails in my merged inbox view and move all of them into the same own folder. 

### Suggested solution

As supported with multi select and SPAM, it would be great to get the option to 'move' as well.

It is already available in unique inboxes or accounts, but not within the merged inbox which is probably the default view for most users. 

### Screenshots / Drawings / Technical details

![Screenshot_20221111_093031](https://user-images.githubusercontent.com/12555687/201298881-2ef6c1f7-49bd-4131-85e5-63f4c683d417.jpg)

**Comment by cketti** [comment] 2022-11-13 22:04
Duplicate of #5709

**Closed by cketti** 2022-11-13 22:04 UTC
Labels: enhancement
