### ISSUE TITLE
Account/Profile icons settings

### ISSUE THREAD

**Issue by saloniamatteo** [thundernest/k-9#6146] opened 2022-07-05 09:18 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.100

### Problem you are trying to solve

Hello everyone,
I think K9-Mail should implement a settings menu where the user can choose a custom account/profile icon, instead of trying to import the icon from contacts (feature which could be used alongside the custom picture)

### Suggested solution

(Implement menu described above)

For example, we could have a settings menu in the specific account/profile, with the setting described above, and the user's going to be able to choose to either have no profile picture, import it from contacts (if the email is found in a contact), or to choose a custom picture.

**Comment by saloniamatteo** [comment] 2022-07-05 09:20
I don't know how this would work with providers like gmail, yahoo, etc., but for people like me who have their own mail server this would be a great addition to this mail client of yours.

**Comment by cketti** [comment] 2022-07-05 09:21
Duplicate of #5509

**Closed by cketti** 2022-07-05 09:21 UTC
Labels: enhancement
