### ISSUE TITLE
Catch-all/Wildcard Identity

### ISSUE THREAD

**Issue by ryancdotorg** [thundernest/k-9#7020] opened 2023-06-23 09:53 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.707

### Problem you are trying to solve

Note that this is essentially a duplicate of #935, which has been locked for some reason. I [pledged $250 towards it](https://app.bountysource.com/issues/28901565-enhance-k9-mail-identity-selection) over seven years ago and apparently forgot about it. As far as I know, it is still eligible to be claimed. Feel free to close this as duplicate and note on the other ticket that there's a bounty on it.

I make *heavy* use of email aliases. When replying to an email, I would like to have my from address and name to be set based on the envelope to address, e.g. an `Envelope-to`, `X-Original-To`, `To`, or `Cc` header, even if it has not already been configured as an identity.

### Suggested solution

Example implementations:

[NeoMutt](https://neomutt.org/guide/configuration.html#alternates), see also [reverse_name](https://neomutt.org/guide/reference.html#reverse-name)

[RoundCube via plugin](https://github.com/r3c/custom_from)

My use case would be addressed by being able to list domains, but I have seen other implementations offering wildcards or regular expressions to be specified.

**Comment by cketti** [comment] 2023-06-23 11:23
The issue was locked, not closed. It also already contains a link to the bounty source page: https://github.com/thundernest/k-9/issues/935#issuecomment-559649074

We don't need another issue to track this feature request.

Duplicate of #935

**Closed by cketti** 2023-06-23 11:23 UTC
Labels: enhancement
