### ISSUE TITLE
Additional SMTP-only configurations

### ISSUE THREAD

**Issue by Starbase12** [thundernest/k-9#6917] opened 2023-05-23 20:44 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.602

### Problem you are trying to solve

Sometimes it can be helpful to send an mail via different SMTP server. E.g. from your subdomain name. Without configuring a whole new mailbox (incoming & outgoing folders) it seems to be not possible. 

### Suggested solution

I would like to add multiple SMTP configurations to an already existing postbox configuration. Alternatively it should be possible to exclude the 2nd configured mailbox completely from the "shared-inbox" view. Without this features every mail is displayed twice.

**Comment by cketti** [comment] 2023-05-23 20:54
Duplicate of #1117

You can configure which folders are included in the Unified Inbox, see https://docs.k9mail.app/en/6.400/settings/folder/#unify

**Closed by cketti** 2023-05-23 20:54 UTC
Labels: enhancement
