### ISSUE TITLE
automatically set from address for wildcard domains

### ISSUE THREAD

**Issue by dorianim** [thundernest/k-9#7016] opened 2023-06-22 11:06 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.602

### Problem you are trying to solve

I have a wildcard mail-address, where I receive all mails `*@mydomain.com`. 
When I reply to those emails, I would like to use the `to` address from the received mail as my `from` address in the reply.

### Suggested solution

Add an option to allow the `from` address in a reply to be set automatically based on the `to` address of the received mail.

**Comment by cketti** [comment] 2023-06-22 11:12
Duplicate of #935

**Closed by cketti** 2023-06-22 11:12 UTC
Labels: enhancement
