### ISSUE TITLE
Set optional PIN for opening the app

### ISSUE THREAD

**Issue by ontheair81** [thundernest/k-9#7019] opened 2023-06-23 07:41 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.602

### Problem you are trying to solve

There are situations, where I give the phone out of my hands for a short time - for example, letting a friend do a call, showing them some pictures in the gallery, etc.

They could easily start K-9 Mail and read mails.

### Suggested solution

Provide the option to set a PIN when starting the app. Nothing fancy, no encryption. Just a PIN that locks the GUI.

I know this feature from other popular mail apps on Android (not sure if I am allowed the mentien the names here), and I am used to have this possibility.

**Comment by cketti** [comment] 2023-06-23 11:19
Duplicate of #753

**Closed by cketti** 2023-06-23 11:19 UTC
Labels: enhancement
