### ISSUE TITLE
Allow "move"/"copy" between different accounts/servers like betterbird/thunderbird.

### ISSUE THREAD

**Issue by vdbhb59** [thundernest/k-9#6628] opened 2023-02-04 19:25 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.503

### Problem you are trying to solve

I use betterbird for my PC. There I can move emails and copy as well between different accounts.
Example: Account1 is say a yahoo account. Account2 is say outlook. Account3 is say my own hosted domain, and so on..

### Suggested solution

Allow move and copy feature between different folders and accounts. Like move/copy say email-abc from say yahoo to own domain folder.

This functionality is present with betterbird and thunderbird as well.

The copy will make a copy of the email in the copy to server/account-folder. Whereas the move option will remove the email from the "FROM" server/account-folder and move it completely to the "TO" server/account-folder.

Note:
1. When the move functionality is invoked and run, the email/entry/file will be completely moved from the source server and will not be present even in the deleted/trash folder.
2. When one server tries to contact the other (copy/move), the second server will obviously authenticate the user password, just like it does in betterbird/thunderbird.
3. The email/file/entry will be moved LIKE TO LIKE / As-Is state (with every property, headers, footers, dkim etc.). Basically like exporting an eml/mbox file and importing it.

### Screenshots / Drawings / Technical details

1. Open an email in account 1
2. Open the 3 dots sub-menu to select a function
3. Click copy/move
4. The list of folders shown to move or copy will reflect all available accounts & folders just like betterbird/thunderbird.

**Comment by vdbhb59** [comment] 2023-02-04 19:27
Please let me know if I missed anything or if I need to add anything. Kindly tag me to give me a nudge.

**Comment by cketti** [comment] 2023-02-04 19:30
Duplicate of #760

**Closed by cketti** 2023-02-04 19:30 UTC
Labels: enhancement
