### ISSUE TITLE
Create Folders

### ISSUE THREAD

**Issue by ryanleesipes** [thundernest/k-9#6634] opened 2023-02-07 04:05 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.506

### Problem you are trying to solve

Cannot create a new folder within K-9 Mail.

### Suggested solution

Give the ability to create a folder as part of the folder management redesign. Also add create folder as an option to the "move" feature.

**Comment by cketti** [comment] 2023-03-14 12:21
Duplicate of #1389

**Closed by cketti** 2023-03-14 12:21 UTC
Labels: enhancement, design

**Comment by marker10** [comment] 2023-07-20 20:19
Is it possible to add the function to create folders? In Gmail, create the labels.
