### ISSUE TITLE
View Individual Mail should show sender's mail by default

### ISSUE THREAD

**Issue by adeorato** [thundernest/k-9#6749] opened 2023-03-11 09:17 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.400

### Problem you are trying to solve

When I get a mail from "Company Name <phishing@example.com", K9 shows in the individual mail view only the chosen name, but not the from mail adress by default.
The mail adress is a really good indicator if it is phishing or not.

So I am not sure, if this a Feature Request or a bug report, since the default behaviour is phishing supporting and therefore it is also security relevant.

### Suggested solution

Show the full FROM header always in the single mail view, at least when the contact is not saved in the adress book

### Screenshots / Drawings / Technical details

Current UI:
Subject
<Avatar> Name from Part
                TO: Name of recpient

My change suggests an extra line 

Subject
<Avatar> Name FROM Part
                Email FROM part
                TO: Name of recpient

**Comment by Fraetor** [comment] 2023-03-12 11:04
Currently even holding on the name doesn't show you the sending address. While you can configure in the settings to show just them email address instead, you can't display both.

My preference would be to display is as `Joe Bloggs <joebloggs@example.com>`.

**Comment by cketti** [comment] 2023-03-14 11:55
Duplicate of #1119

**Closed by cketti** 2023-03-14 11:55 UTC
Labels: enhancement
