### ISSUE TITLE
View/open attachment when composing message

### ISSUE THREAD

**Issue by manne01** [thundernest/k-9#4879] opened 2020-07-15 19:52 UTC
### Expected behavior
I want to be able to open a attachment from a email draft

### Actual behavior
The attachment is shown but I cannot open it

### Steps to reproduce
1. add attachment to a email draft and save+close the draft
2. open the draft again -> attachment is shown but cannot be opened

### Environment
K-9 Mail version: 5.717
Android version: 10
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2022-09-09 18:06
Duplicate of #1634

This particular case should also no longer be an issue once #4163 is implemented.

**Closed by cketti** 2022-09-09 18:06 UTC
Labels: enhancement
