### ISSUE TITLE
New version: still no collapsed folders or wordwrapped folder names

### ISSUE THREAD

**Issue by Dave-Rado** [thundernest/k-9#6855] opened 2023-04-25 22:24 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.601

### Problem you are trying to solve

Folders are extremely difficult to navigate, partly because they are fully expanded, so one has to scroll a long way to find anything; and also because they are severely concatenated instead of wordwrapped and take up less than the width of the screen, so that a huge amount of the folder path is replaced with three dots.

### Suggested solution

1) Please could the folders be collapsed until one expands them? I have about 10 main folders but many hundreds of sub-folders and sub-sub-folders, so finding a folder when they are all fully expanded is almost impossible.

2) Please could the folder names be wordwrapped instead of concatenated (ideally by default but at least as an option in settings) and take up the full width of the screen - as they already when you select "Manage Folders"? 

The lack of these two features have been a serious drawback to using K9Mail for a long time, so it's extremely disappointing that you've just released a major upgrade without addressing this. IMO it's far more important than any of the mostly cosmetic changes that you've made.

Dave

**Comment by cketti** [comment] 2023-04-26 00:25
Improving the folder view is on the [roadmap](https://developer.thunderbird.net/planning/android-roadmap).

Duplicate of #630

**Closed by cketti** 2023-04-26 00:25 UTC
Labels: enhancement
