### ISSUE TITLE
Undo button when deleting an message with the swipe action

### ISSUE THREAD

**Issue by N1c093** [thundernest/k-9#6593] opened 2023-01-18 15:25 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.502

### Problem you are trying to solve

Some versions ago the newest swipe actions where build into K-9. These swipe actions are working pretty fine to mark or delete an e-mail.
Sadly when you delete an e-mail with the swipe action you can't undo it. I happens to me a few time, that I deleted a mail with the swipe action and can't undo it. I had to manually search the message in the trash folder.

### Suggested solution

When you delete a message with the swipe action, there should be a small message on the buttom of the screen to undo it. This message should disappear after a few secons. Like in gmail or outlook app for android.
See example screenshot below.

### Screenshots / Drawings / Technical details

![image](https://user-images.githubusercontent.com/59510296/213211689-8ededdc4-5ae8-4126-9190-afbb6458be04.png)

**Comment by cketti** [comment] 2023-01-18 15:30
Duplicate of #624

**Closed by cketti** 2023-01-18 15:30 UTC
Labels: enhancement
