### ISSUE TITLE
UX: quicky switch between inboxes

### ISSUE THREAD

**Issue by marcvangend** [thundernest/k-9#6157] opened 2022-07-11 06:31 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.000

### Problem you are trying to solve

As a user who does not want to use a unified inbox, I want to be able to quickly switch between inboxes.

### Suggested solution

The list of inboxes should be only 1 click/tap/gesture away. (Currently, it's 2 taps.)

**Comment by cketti** [comment] 2023-10-19 09:43
Closing this as a duplicate of an issue that is newer, but which contains a more concrete example of what the UI could look like.

Duplicate of #7260

**Closed by cketti** 2023-10-19 09:43 UTC
Labels: enhancement
