### ISSUE TITLE
Use "to" address as "from" address when replying

### ISSUE THREAD

**Issue by bobemoe** [thundernest/k-9#7150] opened 2023-08-31 19:16 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.602

### Problem you are trying to solve

When I reply to an email, the from address is incorrect for my catch-all mail domain setup.

### Suggested solution

Whatever the "To" address was on the email that caused me to receive it, should be used as the "From" address when I reply to it. Even if it is not set up as an alias/identity within k9mail.

### Screenshots / Drawings / Technical details

This was discussed in depth in #935 and some very clear use cases were given, however it seems that the reasoning was not fully understood and the issue is now locked. I have read this issue in complete several times and am convinced all the technical details and solution are present and the locking is unjust due to misunderstanding of the catch-all use case.

**Comment by cketti** [comment] 2023-08-31 22:18
Issue #935 was locked because commenters weren't adding any useful information, just noise. Still, it's a feature we want to add eventually. That's why the issue wasn't closed and is still open.

Duplicate of #935.

**Closed by cketti** 2023-08-31 22:18 UTC
Labels: enhancement
