### ISSUE TITLE
Search Bar Redesign

### ISSUE THREAD

**Issue by harish-kumaran** [thundernest/k-9#6991] opened 2023-06-16 11:12 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.705

### Problem you are trying to solve

The search bar is very outdated to recent design standards and does not go well with modern android standards and does not even come close to other email clients UI/UX.

### Suggested solution

~Redesign the search bar just like the username login screen.
~Open the search page when clicking the search icon rather then simply activating the search bar
optional note : doing this could also help tags and filter search be available since it's all possible in a new page rather than just a bar.

### Screenshots / Drawings / Technical details

![ResizedImage_2023-06-16_16-35-43_2162](https://github.com/thundernest/k-9/assets/135484820/11bee475-5248-4304-a1e2-285531d5ad5e)

This image belongs to another open source app store's search function. It also implements tagging similarly could be done to Thunderbird.

**Comment by cketti** [comment] 2023-06-16 12:03
Duplicate of #4513

**Closed by cketti** 2023-06-16 12:03 UTC
Labels: enhancement
