### ISSUE TITLE
Please add optinal biometric or pin lock to app

### ISSUE THREAD

**Issue by jorgevierag** [thundernest/k-9#7186] opened 2023-09-21 05:31 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.602

### Problem you are trying to solve

There's no specific protection to the app. I have many accounts and if I lend my unlocked phone to someone, I don't want him to see my emails

### Suggested solution

Add optional pin or biometric lock

**Comment by cketti** [comment] 2023-09-21 11:08
Duplicate of #753

**Closed by cketti** 2023-09-21 11:08 UTC
Labels: enhancement
