### ISSUE TITLE
Display full email address info in email message header

### ISSUE THREAD

**Issue by markokocic** [thundernest/k-9#6124] opened 2022-06-20 11:42 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.000

### Problem you are trying to solve

In the message list and in the message screen, sender, recipient and other email addresses are not displayed fully.
Depending on the settings, it's either senders name or email that is displayed.

E.g it's either `Firstname Lastname` or `fname.last@example.com` that is displayed. Name can be either what was provided by the sender, or taken from the personal address book.

This is problematic in cases where one contact has multiple emails (e.g. private, business, alternate, ...) Than you either see his name only, without knowing which email, or you see only an email, which is not always clear to which contact it belongs.

### Suggested solution

Mail should be displayed by default in full, like `Whatever descriptive name <fname.lname@example.com>` which is a standard mail format.

Alternatively, it can be a config option whether to display both Name and Email or keep the current behaviour.

**Comment by cketti** [comment] 2022-07-05 13:00
Duplicate of #1119

**Closed by cketti** 2022-07-05 13:00 UTC
Labels: enhancement
