### ISSUE TITLE
Please support rich text

### ISSUE THREAD

**Issue by Dave-Rado** [thundernest/k-9#6856] opened 2023-04-25 22:33 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.601

### Problem you are trying to solve

Every time I want to use rich text, such as **bold text**, or [embedded links](https://github.com/thundernest/k-9/issues/6856), or inline images:
![inspired-lightbulb-character-light-bulb-aha-moment-eps-vector-illustration-52223925](https://user-images.githubusercontent.com/25348746/234420246-556f8c01-2008-4661-835f-de5b422d0f20.jpg) 
I have to use another email client. So it's hugely disappointing that you've just released a major upgrade without addressing this. Using asterixes to denote bold belongs to the stone age, as does displaying long urls instead of links, as does being unable to have an inline image in an email.  

### Suggested solution

Please add support for rich text emails, including text formatting such as bold, and support for  embedded links and inline images.

**Comment by cketti** [comment] 2023-04-26 00:26
Duplicate of #1745

**Closed by cketti** 2023-04-26 00:26 UTC
Labels: enhancement
