### ISSUE TITLE
Export a email as EML file

### ISSUE THREAD

**Issue by xmha97** [thundernest/k-9#6465] opened 2022-11-07 22:59 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.202

### Problem you are trying to solve

I need EML export feature.

### Suggested solution

I need EML export feature.

**Comment by cketti** [comment] 2022-11-07 23:22
Duplicate of #1498

**Closed by cketti** 2022-11-07 23:22 UTC
Labels: enhancement
