### ISSUE TITLE
Save e-mail to file

### ISSUE THREAD

**Issue by gtomassoni** [thundernest/k-9#6720] opened 2023-03-05 22:49 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.400

### Problem you are trying to solve

It seems to me there is no way to save an e-mail to a file in K-9.

This feature is present in most e-mail clients and I would appreciate it in K-9.

### Suggested solution

On an opened e-mail, the contextual menu should show a new option to save the e-mail to a file.

The file format could be as simple as RFC 822.

**Comment by cketti** [comment] 2023-03-06 11:59
Duplicate of #1498

**Closed by cketti** 2023-03-06 11:59 UTC
Labels: enhancement
