### ISSUE TITLE
Keep flagged / starred messages

### ISSUE THREAD

**Issue by kroeckx** [thundernest/k-9#7192] opened 2023-09-23 10:30 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.602

### Problem you are trying to solve

I star / flag e-mails I will need to follow-up on. I've set it up to keep the last 1000 messages, which is about 1 month of emails. But if that email is not part of the  last 1000 messages, K9 will just remove it from the inbox and I don't see it anymore.

### Suggested solution

Always keep all the starred messages.

**Comment by cketti** [comment] 2023-10-01 15:13
Duplicate of #2621

**Closed by cketti** 2023-10-01 15:13 UTC
Labels: enhancement
