### ISSUE TITLE
Add "Not Junk" = "Move Inbox"

### ISSUE THREAD

**Issue by kripper** [thundernest/k-9#6090] opened 2022-05-31 20:59 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

5.806

### Problem you are trying to solve

(This is an easy-to-add and cool feature request :-)

Add a "Not Spam" menu entry in the "Move | Copy | Add star | Select all" menu (the menu that is displayed when pressing the 3 dots menu inside the "Junk" folder).

Action to perform: "Move > Inbox" (it's just a shortcut).

Motivation: Sometimes you find a message in the Spam or Junk folder and want to mark it as "Not Spam" or (at least) move it back to the Inbox folder where it belongs.

This will be very handy and not invasive since we only need to show this option when we are navigating the Spam/Junk folder.

### Suggested solution

Add a "Not Spam" menu entry in the "Move | Copy | Add star | Select all" menu (the menu that is displayed when pressing the 3 dots menu inside the "Junk" folder).

Action to perform: "Move > Inbox" (it's just a shortcut).

### Screenshots / Drawings / Technical details

Imagine this context menu:

Not Spam
Move
Copy
Add star
Select all

**Comment by cketti** [comment] 2022-07-13 09:04
Duplicate of #1793

**Closed by cketti** 2022-07-13 09:04 UTC
Labels: enhancement

**Comment by pwd-github** [comment] 2024-05-31 12:44
Just came to request this
