### ISSUE TITLE
Ability to move multiple messages from unified inbox

### ISSUE THREAD

**Issue by mickenordin** [thundernest/k-9#7109] opened 2023-08-03 14:50 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.602

### Problem you are trying to solve

The default view in k9 is the unified inbox, which is great. It is currently possible to select several messages in the unified inbox and then delete them or archive them, but it is not possible to move them to a folder in a particular mailbox.

I understand that this is probably due to the fact that it might seem strange to move mail from one mailbox in to a folder of another mailbox BUT this feature is available in other clients and it is useful. It can be viewed as an instant forward of a mail to yourself.

### Suggested solution

My preffered solution for this would be to make it so that it is possible to move any piece of mail in the unified inbox in to any folder of any mailbox. However I would also think that it would be an improvement to be able to move multiple mails into a folder if and only if they are in the same mailbox (i.e. the move button could be greyed out if mails from several mailboxes were selected).

### Screenshots / Drawings / Technical details

![IMG_20230803_164804](https://github.com/thundernest/k-9/assets/1281830/51b97cd9-0890-4bf3-a2e2-ab172c3a1967)

Add a move button here.

**Comment by cketti** [comment] 2023-08-03 15:06
Duplicate of #5709

**Closed by cketti** 2023-08-03 15:06 UTC
Labels: enhancement
