### ISSUE TITLE
Schedule emails to send

### ISSUE THREAD

**Issue by heberjeur** [thundernest/k-9#6419] opened 2022-10-22 15:01 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.309

### Problem you are trying to solve

We can schedule  emails to send at a later time. 

### Suggested solution

Scheduled emails may be sent a few minutes,days after the scheduled time.
I need at work to send emails from 8:00 to 15:00

**Comment by cketti** [comment] 2022-10-22 15:02
Duplicate of #688

**Closed by cketti** 2022-10-22 15:02 UTC
Labels: enhancement
