### ISSUE TITLE
Swipe for delete

### ISSUE THREAD

**Issue by Lycama8876** [thundernest/k-9#6140] opened 2022-06-30 20:32 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.00

### Problem you are trying to solve

Adding swipe for delete will be so cool

### Suggested solution

Swipe action

**Comment by cketti** [comment] 2022-07-04 11:21
Duplicate of #1426

**Closed by cketti** 2022-07-04 11:21 UTC
Labels: enhancement
